server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.0.130.233:3306/test?characterEncoding=utf8
    username: root
    password: mysql
  jpa:
    database: MYSQL
    show-sql: true

    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
